# Generated by Django 3.2.4 on 2023-10-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('recever', models.CharField(max_length=30)),
                ('chat', models.TextField()),
                ('Date_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
